-- ServerFlow initial schema (Phase 9): tenants, API keys, model configs, benchmark runs.
--
-- Conventions: ids are prefixed random strings generated by the application (ten_, key_, bench_);
-- every status is a constrained text column; quotas of 0 mean "no limit configured" (Phase 8
-- enforces them); allowed_models NULL means every model, an empty array means none.
-- API key secrets are never stored: only the public prefix and SHA-256 of the secret.

CREATE TABLE tenants (
    id                      text        PRIMARY KEY,
    name                    text        NOT NULL UNIQUE
        CONSTRAINT tenants_name_format CHECK (name ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$' AND name !~ '^(ten|key)_'),
    status                  text        NOT NULL DEFAULT 'active'
        CONSTRAINT tenants_status_known CHECK (status IN ('active', 'suspended')),
    requests_per_minute     integer     NOT NULL DEFAULT 0 CONSTRAINT tenants_rpm_nonneg CHECK (requests_per_minute >= 0),
    tokens_per_minute       integer     NOT NULL DEFAULT 0 CONSTRAINT tenants_tpm_nonneg CHECK (tokens_per_minute >= 0),
    max_concurrent_requests integer     NOT NULL DEFAULT 0 CONSTRAINT tenants_conc_nonneg CHECK (max_concurrent_requests >= 0),
    allowed_models          text[],
    priority                integer     NOT NULL DEFAULT 1 CONSTRAINT tenants_priority_range CHECK (priority BETWEEN 0 AND 2),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id           text        PRIMARY KEY,
    tenant_id    text        NOT NULL REFERENCES tenants (id),
    label        text        NOT NULL DEFAULT '' CONSTRAINT api_keys_label_len CHECK (char_length(label) <= 128),
    prefix       text        NOT NULL UNIQUE CONSTRAINT api_keys_prefix_format CHECK (prefix ~ '^[0-9a-f]{8}$'),
    secret_hash  bytea       NOT NULL CONSTRAINT api_keys_hash_len CHECK (octet_length(secret_hash) = 32),
    status       text        NOT NULL DEFAULT 'active' CONSTRAINT api_keys_status_known CHECK (status IN ('active', 'revoked')),
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz,
    revoked_at   timestamptz,
    last_used_at timestamptz,
    CONSTRAINT api_keys_revoked_consistent CHECK ((status = 'revoked') = (revoked_at IS NOT NULL))
);

CREATE INDEX api_keys_tenant_id_idx ON api_keys (tenant_id);

CREATE TABLE models (
    name             text        PRIMARY KEY CONSTRAINT models_name_len CHECK (char_length(name) BETWEEN 1 AND 128),
    status           text        NOT NULL DEFAULT 'enabled' CONSTRAINT models_status_known CHECK (status IN ('enabled', 'disabled')),
    display_name     text        NOT NULL DEFAULT '',
    max_tokens_limit integer     CONSTRAINT models_max_tokens_pos CHECK (max_tokens_limit IS NULL OR max_tokens_limit > 0),
    notes            text        NOT NULL DEFAULT '',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE benchmark_runs (
    id                  text             PRIMARY KEY,
    created_at          timestamptz      NOT NULL DEFAULT now(),
    git_commit          text             NOT NULL DEFAULT '',
    git_dirty           boolean          NOT NULL DEFAULT false,
    model               text             NOT NULL,
    worker_count        integer          NOT NULL CONSTRAINT benchmark_runs_workers_nonneg CHECK (worker_count >= 0),
    gpu_type            text             NOT NULL DEFAULT '',
    scheduler           text             NOT NULL DEFAULT '',
    concurrency_or_rate text             NOT NULL DEFAULT '',
    workload            text             NOT NULL DEFAULT '',
    prompt_distribution jsonb,
    max_tokens          integer          CONSTRAINT benchmark_runs_max_tokens_pos CHECK (max_tokens IS NULL OR max_tokens > 0),
    duration_seconds    double precision NOT NULL DEFAULT 0 CONSTRAINT benchmark_runs_duration_nonneg CHECK (duration_seconds >= 0),
    seed                bigint,
    repeat_index        integer          NOT NULL DEFAULT 0 CONSTRAINT benchmark_runs_repeat_nonneg CHECK (repeat_index >= 0),
    schema_version      integer          NOT NULL CONSTRAINT benchmark_runs_schema_pos CHECK (schema_version > 0),
    result              jsonb            NOT NULL
);

CREATE INDEX benchmark_runs_created_at_idx ON benchmark_runs (created_at DESC);
