package redis

import (
	"context"
	"encoding/json"
	"sync"
	"sync/atomic"
	"time"
)

// Recorder writes best-effort request metadata: request:{id} -> {tenant, model, worker, attempt} with a TTL
// (spec section 18, request routing hints). Nothing reads it yet; it is for debugging and later sticky
// routing. Record never blocks and never fails a request: records go through a bounded queue to a few
// background writers, and are dropped when the queue is full, when Redis is backing off, or on any error.
type Recorder struct {
	c       *Client
	ttl     time.Duration
	q       chan record
	dropped atomic.Int64
	written atomic.Int64
}

type record struct {
	key, value string
}

const (
	recorderQueue   = 1024
	recorderWorkers = 2
)

// NewRecorder returns a recorder writing through c with the given TTL. Start it with Run.
func NewRecorder(c *Client, ttl time.Duration) *Recorder {
	return &Recorder{c: c, ttl: ttl, q: make(chan record, recorderQueue)}
}

// Record queues one record. requestID is generated by the gateway, never taken from the client.
func (r *Recorder) Record(requestID, tenantID, model, worker string, attempt int) {
	if down, _ := r.c.Down(); down {
		r.dropped.Add(1)
		return
	}
	v, err := json.Marshal(struct {
		Tenant  string `json:"tenant,omitempty"`
		Model   string `json:"model"`
		Worker  string `json:"worker"`
		Attempt int    `json:"attempt"`
	}{tenantID, model, worker, attempt})
	if err != nil {
		return
	}
	select {
	case r.q <- record{"request:{" + requestID + "}", string(v)}:
	default:
		r.dropped.Add(1)
	}
}

// Dropped counts records not written (queue full, Redis backing off, or an error).
func (r *Recorder) Dropped() int64 { return r.dropped.Load() }

// Written counts records stored.
func (r *Recorder) Written() int64 { return r.written.Load() }

// Run writes queued records until ctx ends.
func (r *Recorder) Run(ctx context.Context) {
	var wg sync.WaitGroup
	for i := 0; i < recorderWorkers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				select {
				case <-ctx.Done():
					return
				case rec := <-r.q:
					if err := r.c.Set(ctx, rec.key, rec.value, r.ttl); err != nil {
						r.dropped.Add(1)
					} else {
						r.written.Add(1)
					}
				}
			}
		}()
	}
	wg.Wait()
}
